CREATE TABLE `cp1_1_ftp_groups` (
  `id` int(20) NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `groupname` varchar(60) NOT NULL default '',
  `gid` int(5) NOT NULL default '0',
  `members` longtext NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `groupname` (`groupname`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_ftp_users` (
  `id` int(20) NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `username` varchar(255) NOT NULL default '',
  `uid` int(5) NOT NULL default '0',
  `gid` int(5) NOT NULL default '0',
  `password` varchar(20) NOT NULL default '',
  `homedir` varchar(255) NOT NULL default '',
  `shell` varchar(255) NOT NULL default '/bin/false',
  `login_enabled` enum('N','Y') NOT NULL default 'N',
  `login_count` int(15) NOT NULL default '0',
  `last_login` datetime NOT NULL default '0000-00-00 00:00:00',
  `up_count` int(15) NOT NULL default '0',
  `up_bytes` bigint(30) NOT NULL default '0',
  `down_count` int(15) NOT NULL default '0',
  `down_bytes` bigint(30) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_mail_traffic` (
  `userID` int(11) NOT NULL default '0',
  `domain` varchar(80) NOT NULL default '',
  `bytes` int(10) unsigned NOT NULL default '0',
  `source` varchar(4) default NULL,
  KEY `userID` (`userID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_mail_users` (
  `id` int(11) NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `email` varchar(255) NOT NULL default '',
  `username` varchar(255) NOT NULL default '',
  `password` varchar(128) NOT NULL default '',
  `password_enc` varchar(128) NOT NULL default '',
  `uid` int(11) NOT NULL default '0',
  `gid` int(11) NOT NULL default '0',
  `homedir` varchar(255) NOT NULL default '',
  `maildir` varchar(255) NOT NULL default '',
  `postfix` enum('Y','N') NOT NULL default 'Y',
  `domainid` int(11) NOT NULL default '0',
  `quota` bigint(13) NOT NULL default '0',
  `pop3` tinyint(1) NOT NULL default '1',
  `imap` tinyint(1) NOT NULL default '1',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_mail_virtual` (
  `id` int(11) NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `email` varchar(255) NOT NULL default '',
  `email_full` varchar(255) NOT NULL default '',
  `destination` text NOT NULL,
  `domainid` int(11) NOT NULL default '0',
  `popaccountid` int(11) NOT NULL default '0',
  `iscatchall` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `email` (`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_modules_maildrop` (
  `spam` enum('Y','N') NOT NULL default 'N',
  `greylisting` enum('1','0') NOT NULL default '1',
  `email` varchar(128) NOT NULL default '',
  PRIMARY KEY  (`email`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_modules_mailman` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `domainid` int(11) unsigned NOT NULL default '0',
  `listname` varchar(20) NOT NULL default '',
  `domain` varchar(36) NOT NULL default '',
  `owner` varchar(80) NOT NULL default '',
  `list_address` varchar(255) NOT NULL default '',
  `description` varchar(150) NOT NULL default '',
  `password` varchar(20) NOT NULL default '',
  `flag` tinyint(1) NOT NULL default '0',
  `created` datetime NOT NULL,
  `transport` varchar(30) NOT NULL default 'mailman:',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `panel_admins` (
  `adminid` int(11) unsigned NOT NULL auto_increment,
  `loginname` varchar(50) NOT NULL default '',
  `password` varchar(50) NOT NULL default '',
  `name` varchar(255) NOT NULL default '',
  `email` varchar(255) NOT NULL default '',
  `def_language` varchar(255) NOT NULL default '',
  `ip` tinyint(4) NOT NULL default '-1',
  `customers` int(15) NOT NULL default '0',
  `customers_used` int(15) NOT NULL default '0',
  `customers_see_all` tinyint(1) NOT NULL default '0',
  `domains` int(15) NOT NULL default '0',
  `domains_used` int(15) NOT NULL default '0',
  `domains_see_all` tinyint(1) NOT NULL default '0',
  `caneditphpsettings` tinyint(1) NOT NULL default '0',
  `change_serversettings` tinyint(1) NOT NULL default '0',
  `edit_billingdata` tinyint(1) NOT NULL default '0',
  `diskspace` int(15) NOT NULL default '0',
  `diskspace_used` int(15) NOT NULL default '0',
  `mysqls` int(15) NOT NULL default '0',
  `mysqls_used` int(15) NOT NULL default '0',
  `emails` int(15) NOT NULL default '0',
  `emails_used` int(15) NOT NULL default '0',
  `email_accounts` int(15) NOT NULL default '0',
  `email_accounts_used` int(15) NOT NULL default '0',
  `email_forwarders` int(15) NOT NULL default '0',
  `email_forwarders_used` int(15) NOT NULL default '0',
  `email_quota` bigint(13) NOT NULL default '0',
  `email_quota_used` bigint(13) NOT NULL default '0',
  `ftps` int(15) NOT NULL default '0',
  `ftps_used` int(15) NOT NULL default '0',
  `tickets` int(15) NOT NULL default '-1',
  `tickets_used` int(15) NOT NULL default '0',
  `subdomains` int(15) NOT NULL default '0',
  `subdomains_used` int(15) NOT NULL default '0',
  `traffic` int(15) NOT NULL default '0',
  `traffic_used` int(15) NOT NULL default '0',
  `deactivated` tinyint(1) NOT NULL default '0',
  `lastlogin_succ` int(11) unsigned NOT NULL default '0',
  `lastlogin_fail` int(11) unsigned NOT NULL default '0',
  `loginfail_count` int(11) unsigned NOT NULL default '0',
  `reportsent` tinyint(4) unsigned NOT NULL default '0',
  `firstname` varchar(255) NOT NULL default '',
  `title` varchar(255) NOT NULL default '',
  `company` varchar(255) NOT NULL default '',
  `street` varchar(255) NOT NULL default '',
  `zipcode` varchar(255) NOT NULL default '',
  `city` varchar(255) NOT NULL default '',
  `country` varchar(255) NOT NULL default '',
  `phone` varchar(255) NOT NULL default '',
  `fax` varchar(255) NOT NULL default '',
  `taxid` varchar(255) NOT NULL default '',
  `contract_date` date NOT NULL,
  `contract_number` varchar(255) NOT NULL default '',
  `contract_details` text NOT NULL,
  `included_domains_qty` int(11) NOT NULL default '0',
  `included_domains_tld` varchar(255) NOT NULL default '',
  `additional_traffic_fee` decimal(10,2) NOT NULL default '0.00',
  `additional_traffic_unit` bigint(30) NOT NULL default '0',
  `additional_diskspace_fee` decimal(10,2) NOT NULL default '0.00',
  `additional_diskspace_unit` bigint(30) NOT NULL default '0',
  `taxclass` int(11) NOT NULL default '0',
  `setup_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_length` int(11) NOT NULL default '0',
  `interval_type` varchar(1) NOT NULL default 'm',
  `interval_payment` tinyint(1) NOT NULL default '0',
  `calc_tax` tinyint(1) NOT NULL default '1',
  `term_of_payment` int(11) NOT NULL default '0',
  `payment_every` int(11) NOT NULL default '0',
  `payment_method` int(11) NOT NULL default '0',
  `bankaccount_holder` text NOT NULL,
  `bankaccount_number` varchar(255) NOT NULL default '',
  `bankaccount_blz` varchar(255) NOT NULL default '',
  `bankaccount_bank` varchar(255) NOT NULL default '',
  `service_active` tinyint(1) NOT NULL default '0',
  `servicestart_date` date NOT NULL,
  `serviceend_date` date NOT NULL,
  `lastinvoiced_date` date NOT NULL,
  `lastinvoiced_date_traffic` date NOT NULL,
  `lastinvoiced_date_diskspace` date NOT NULL,
  `customer_categories_once` text NOT NULL,
  `customer_categories_period` text NOT NULL,
  `invoice_fee` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_hosting` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_hosting_customers` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_domains` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_traffic` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_diskspace` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_other` decimal(10,2) NOT NULL default '0.00',
  `can_manage_aps_packages` tinyint(1) NOT NULL default '1',
  `aps_packages` int(5) NOT NULL default '0',
  `aps_packages_used` int(5) NOT NULL default '0',
  PRIMARY KEY  (`adminid`),
  UNIQUE KEY `loginname` (`loginname`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `panel_customers` (
  `customerid` int(11) unsigned NOT NULL auto_increment,
  `loginname` varchar(50) NOT NULL default '',
  `password` varchar(50) NOT NULL default '',
  `adminid` int(11) unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL default '',
  `firstname` varchar(255) NOT NULL default '',
  `company` varchar(255) NOT NULL default '',
  `street` varchar(255) NOT NULL default '',
  `zipcode` varchar(255) NOT NULL default '',
  `city` varchar(255) NOT NULL default '',
  `phone` varchar(255) NOT NULL default '',
  `fax` varchar(255) NOT NULL default '',
  `email` varchar(255) NOT NULL default '',
  `customernumber` varchar(255) NOT NULL default '',
  `def_language` varchar(255) NOT NULL default '',
  `diskspace` bigint(30) NOT NULL default '0',
  `diskspace_used` bigint(30) NOT NULL default '0',
  `mysqls` int(15) NOT NULL default '0',
  `mysqls_used` int(15) NOT NULL default '0',
  `emails` int(15) NOT NULL default '0',
  `emails_used` int(15) NOT NULL default '0',
  `email_accounts` int(15) NOT NULL default '0',
  `email_accounts_used` int(15) NOT NULL default '0',
  `email_forwarders` int(15) NOT NULL default '0',
  `email_forwarders_used` int(15) NOT NULL default '0',
  `email_quota` bigint(13) NOT NULL default '0',
  `email_quota_used` bigint(13) NOT NULL default '0',
  `ftps` int(15) NOT NULL default '0',
  `ftps_used` int(15) NOT NULL default '0',
  `tickets` int(15) NOT NULL default '0',
  `tickets_used` int(15) NOT NULL default '0',
  `subdomains` int(15) NOT NULL default '0',
  `subdomains_used` int(15) NOT NULL default '0',
  `traffic` bigint(30) NOT NULL default '0',
  `traffic_used` bigint(30) NOT NULL default '0',
  `documentroot` varchar(255) NOT NULL default '',
  `standardsubdomain` int(11) NOT NULL default '0',
  `guid` int(5) NOT NULL default '0',
  `ftp_lastaccountnumber` int(11) NOT NULL default '0',
  `mysql_lastaccountnumber` int(11) NOT NULL default '0',
  `deactivated` tinyint(1) NOT NULL default '0',
  `phpenabled` tinyint(1) NOT NULL default '1',
  `lastlogin_succ` int(11) unsigned NOT NULL default '0',
  `lastlogin_fail` int(11) unsigned NOT NULL default '0',
  `loginfail_count` int(11) unsigned NOT NULL default '0',
  `reportsent` tinyint(4) unsigned NOT NULL default '0',
  `imap` tinyint(1) NOT NULL default '0',
  `pop3` tinyint(1) NOT NULL default '0',
  `taxid` varchar(255) NOT NULL default '',
  `title` varchar(255) NOT NULL default '',
  `country` varchar(255) NOT NULL default '',
  `additional_service_description` text NOT NULL,
  `contract_date` date NOT NULL,
  `contract_number` varchar(255) NOT NULL default '',
  `contract_details` text NOT NULL,
  `included_domains_qty` int(11) NOT NULL default '0',
  `included_domains_tld` varchar(255) NOT NULL default '',
  `additional_traffic_fee` decimal(10,2) NOT NULL default '0.00',
  `additional_traffic_unit` bigint(30) NOT NULL default '0',
  `additional_diskspace_fee` decimal(10,2) NOT NULL default '0.00',
  `additional_diskspace_unit` bigint(30) NOT NULL default '0',
  `taxclass` int(11) NOT NULL default '0',
  `setup_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_length` int(11) NOT NULL default '0',
  `interval_type` varchar(1) NOT NULL default 'm',
  `interval_payment` tinyint(1) NOT NULL default '0',
  `calc_tax` tinyint(1) NOT NULL default '1',
  `term_of_payment` int(11) NOT NULL default '0',
  `payment_every` int(11) NOT NULL default '0',
  `payment_method` int(11) NOT NULL default '0',
  `bankaccount_holder` text NOT NULL,
  `bankaccount_number` varchar(255) NOT NULL default '',
  `bankaccount_blz` varchar(255) NOT NULL default '',
  `bankaccount_bank` varchar(255) NOT NULL default '',
  `service_active` tinyint(1) NOT NULL default '0',
  `servicestart_date` date NOT NULL,
  `serviceend_date` date NOT NULL,
  `lastinvoiced_date` date NOT NULL,
  `lastinvoiced_date_traffic` date NOT NULL,
  `lastinvoiced_date_diskspace` date NOT NULL,
  `invoice_fee` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_hosting` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_domains` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_traffic` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_diskspace` decimal(10,2) NOT NULL default '0.00',
  `invoice_fee_other` decimal(10,2) NOT NULL default '0.00',
  `aps_packages` int(5) NOT NULL default '0',
  `aps_packages_used` int(5) NOT NULL default '0',
  PRIMARY KEY  (`customerid`),
  UNIQUE KEY `loginname` (`loginname`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_databases` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `databasename` varchar(255) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_diskspace` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `year` int(4) unsigned zerofill NOT NULL default '0000',
  `month` int(2) unsigned zerofill NOT NULL default '00',
  `day` int(2) unsigned zerofill NOT NULL default '00',
  `stamp` int(11) unsigned NOT NULL default '0',
  `webspace` bigint(30) unsigned NOT NULL default '0',
  `mail` bigint(30) unsigned NOT NULL default '0',
  `mysql` bigint(30) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_domains` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `domain` varchar(255) NOT NULL default '',
  `adminid` int(11) unsigned NOT NULL default '0',
  `customerid` int(11) unsigned NOT NULL default '0',
  `aliasdomain` int(11) unsigned default NULL,
  `documentroot` varchar(255) NOT NULL default '',
  `ipandport` int(11) unsigned NOT NULL default '1',
  `isbinddomain` tinyint(1) NOT NULL default '0',
  `isemaildomain` tinyint(1) NOT NULL default '0',
  `email_only` tinyint(1) NOT NULL default '0',
  `iswildcarddomain` tinyint(1) NOT NULL default '0',
  `subcanemaildomain` tinyint(1) NOT NULL default '0',
  `caneditdomain` tinyint(1) NOT NULL default '1',
  `zonefile` varchar(255) NOT NULL default '',
  `dkim` tinyint(1) NOT NULL default '0',
  `dkim_id` int(11) unsigned NOT NULL,
  `dkim_privkey` text NOT NULL,
  `dkim_pubkey` text NOT NULL,
  `wwwserveralias` tinyint(1) NOT NULL default '1',
  `parentdomainid` int(11) unsigned NOT NULL default '0',
  `openbasedir` tinyint(1) NOT NULL default '0',
  `openbasedir_path` tinyint(1) NOT NULL default '0',
  `safemode` tinyint(1) NOT NULL default '0',
  `speciallogfile` tinyint(1) NOT NULL default '0',
  `specialsettings` text NOT NULL,
  `deactivated` tinyint(1) NOT NULL default '0',
  `bindserial` varchar(10) NOT NULL default '2000010100',
  `ssl` tinyint(4) NOT NULL default '0',
  `ssl_redirect` tinyint(4) NOT NULL default '0',
  `ssl_ipandport` tinyint(4) NOT NULL default '0',
  `add_date` int(11) NOT NULL default '0',
  `registration_date` date NOT NULL,
  `taxclass` int(11) NOT NULL default '0',
  `setup_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_fee` decimal(10,2) NOT NULL default '0.00',
  `interval_length` int(11) NOT NULL default '0',
  `interval_type` varchar(1) NOT NULL default 'y',
  `interval_payment` tinyint(1) NOT NULL default '0',
  `service_active` tinyint(1) NOT NULL default '0',
  `servicestart_date` date NOT NULL,
  `serviceend_date` date NOT NULL,
  `lastinvoiced_date` date NOT NULL,
  `phpsettingid` int(11) unsigned NOT NULL default '1',
  `mod_fcgid_starter` int(4) default '-1',
  `mod_fcgid_maxrequests` int(4) default '-1',
  PRIMARY KEY  (`id`),
  KEY `userID` (`userID`),
  KEY `parentdomain` (`parentdomainid`),
  KEY `domain` (`domain`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_htaccess` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `path` varchar(255) NOT NULL default '',
  `options_indexes` tinyint(1) NOT NULL default '0',
  `error404path` varchar(255) NOT NULL default '',
  `error403path` varchar(255) NOT NULL default '',
  `error500path` varchar(255) NOT NULL default '',
  `error401path` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_htpasswds` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `path` varchar(255) NOT NULL default '',
  `username` varchar(255) NOT NULL default '',
  `password` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_ipsandports` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `ip` varchar(39) NOT NULL default '',
  `port` int(5) NOT NULL default '80',
  `listen_statement` tinyint(1) NOT NULL default '0',
  `namevirtualhost_statement` tinyint(1) NOT NULL default '0',
  `vhostcontainer` tinyint(1) NOT NULL default '0',
  `vhostcontainer_servername_statement` tinyint(1) NOT NULL default '0',
  `specialsettings` text NOT NULL,
  `ssl` tinyint(4) NOT NULL default '0',
  `ssl_cert` tinytext,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_syslog` (
  `logid` bigint(20) NOT NULL auto_increment,
  `action` int(5) NOT NULL default '10',
  `type` int(5) NOT NULL default '0',
  `date` int(15) NOT NULL,
  `user` varchar(50) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY  (`logid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_panel_tasks` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `type` int(11) NOT NULL default '0',
  `data` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `cp1_1_traffic` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `userID` int(11) NOT NULL default '0',
  `year` int(4) unsigned zerofill NOT NULL default '0000',
  `month` int(2) unsigned zerofill NOT NULL default '00',
  `day` int(2) unsigned zerofill NOT NULL default '00',
  `stamp` int(11) unsigned NOT NULL default '0',
  `http` bigint(30) unsigned NOT NULL default '0',
  `ftp_up` bigint(30) unsigned NOT NULL default '0',
  `ftp_down` bigint(30) unsigned NOT NULL default '0',
  `mail` bigint(30) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `userID` (`userID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
